name: dart_console3

description: A package.

homepage: https://github.com/modulovalue/dart_console

version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  ffi: ^1.1.1
  win32: ^2.0.0

dev_dependencies:
  extra_pedantic: ^3.0.0
  hotreloader: ^3.0.1
  test: ^1.16.0
  vector_math: ^2.1.0
